services:
  react-app:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.dev
    build: .
    ports:
      - "5000:5173"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build: .
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]