name: Deploy ReactApp
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code, build, run test
        uses: actions/checkout@v4
        run: docker build -t react-app -f Dockerfile.dev .
        run: docker run -e CI=true react-app npm run test

      - name: Generate a zip
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to ElasticBean
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          application_name: Test-React-App
          environment_name: Test-React-App-env
          existing_bucket_name: elasticbeanstalk-ap-south-1-241533115304
          region: ap-south-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}