name: CI-CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Build Docker image
        run: docker build -t react-app -f Dockerfile.dev .
        
      - name: Run tests
        run: docker run -e CI=true react-app npm run test
